services:
  rabbitMq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports: 
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_nodejs
  loggerapp:
    build: ./loggerMS 
    ports:
      - 80:3000
    volumes:
      - .:/src
    depends_on:
      - "rabbitmq"
    environment:
      NODE_ENV: local
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - rabbitmq_nodejs
networks:
  rabbitmq_nodejs:
    driver: bridge